apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: px87dh1xz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: px87dh1xz-go 
  name: px87dh1xz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: px87dh1xz-go 
