apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: px87dh1xz-go 
  janus-idp.io/tekton: px87dh1xz-go
  backstage.io/kubernetes-id: px87dh1xz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: px87dh1xz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml